#!/bin/bash
# this gives me a list of a number, then the git hash, for all git hashes that have my file

generate_sub_picture() {
    if [[ -f "$1.p8" ]] && [[ ! -f "$1.png" ]]; then
        pico8 -screenshot_scale 3 -x "$1.p8"
        convert -append ~/Desktop/render1.png ~/Desktop/render2.png "$1.png"
    fi
}

git log --pretty=format:"COMMIT %h %n" --name-only |
    tr '\n' ' ' |
    sed -E 's/COMMIT/\n/g' |
    rg '(2023-picodex|2023-pokemon-battle-sim)/\d\d\d-\d\d\d\.p8' |
    tac |
    awk '{print NR " " $1}' |

while read -r number commithash ; do # magic is here
    echo "-------- $commithash:$number"

    FILE1="000--$number"
    FILE2="064--$number"
    FILE3="128--$number"
    FILE4="all--$number"

    if   git show "$commithash":2023-picodex/000-063.p8 >/dev/null 2>&1;            then git show "$commithash":2023-picodex/000-063.p8            | rg -v 'preview|__lua__' | sed 's/__gfx__/__lua__\n#include render.lua\n__gfx__/g' > "$FILE1.p8"
    elif git show "$commithash":2023-picodex/001-064.p8 >/dev/null 2>&1;            then git show "$commithash":2023-picodex/001-064.p8            | rg -v 'preview|__lua__' | sed 's/__gfx__/__lua__\n#include render.lua\n__gfx__/g' > "$FILE1.p8"
    elif git show "$commithash":2023-pokemon-battle-sim/001-064.p8 >/dev/null 2>&1; then git show "$commithash":2023-pokemon-battle-sim/001-064.p8 | rg -v 'preview|__lua__' | sed 's/__gfx__/__lua__\n#include render.lua\n__gfx__/g' > "$FILE1.p8"; fi

    if   git show "$commithash":2023-picodex/064-127.p8 >/dev/null 2>&1;            then git show "$commithash":2023-picodex/064-127.p8            | rg -v 'preview|__lua__' | sed 's/__gfx__/__lua__\n#include render.lua\n__gfx__/g' > "$FILE2.p8"
    elif git show "$commithash":2023-picodex/065-128.p8 >/dev/null 2>&1;            then git show "$commithash":2023-picodex/065-128.p8            | rg -v 'preview|__lua__' | sed 's/__gfx__/__lua__\n#include render.lua\n__gfx__/g' > "$FILE2.p8"
    elif git show "$commithash":2023-pokemon-battle-sim/065-128.p8 >/dev/null 2>&1; then git show "$commithash":2023-pokemon-battle-sim/065-128.p8 | rg -v 'preview|__lua__' | sed 's/__gfx__/__lua__\n#include render.lua\n__gfx__/g' > "$FILE2.p8"; fi

    if   git show "$commithash":2023-picodex/128-151.p8 >/dev/null 2>&1;            then git show "$commithash":2023-picodex/128-151.p8            | rg -v 'preview|__lua__' | sed 's/__gfx__/__lua__\n#include render.lua\n__gfx__/g' > "$FILE3.p8"
    elif git show "$commithash":2023-picodex/129-151.p8 >/dev/null 2>&1;            then git show "$commithash":2023-picodex/129-151.p8            | rg -v 'preview|__lua__' | sed 's/__gfx__/__lua__\n#include render.lua\n__gfx__/g' > "$FILE3.p8"
    elif git show "$commithash":2023-pokemon-battle-sim/129-151.p8 >/dev/null 2>&1; then git show "$commithash":2023-pokemon-battle-sim/129-151.p8 | rg -v 'preview|__lua__' | sed 's/__gfx__/__lua__\n#include render.lua\n__gfx__/g' > "$FILE3.p8"; fi

    generate_sub_picture "$FILE1"
    generate_sub_picture "$FILE2"
    generate_sub_picture "$FILE3"

    if [[ ! -f "$FILE4.png" ]]; then
        echo "CREATING $FILE4.png"
        convert +append "$FILE1.png" "$FILE2.png" "$FILE3.png" "$FILE4.png"
    fi

    echo
done

echo 'And finally creating the gif!'
FIRST=$(fd 'all--\d+\.png' | sort -V | head -n 2 | tail -n 1)
LAST=$(fd 'all--\d+\.png' | sort -V | tail -n 1)
LONG=100
convert -delay $LONG -loop 0 "$FIRST" -delay 5 -loop 0 $(fd 'all--\d+\.png' | sort -V) -delay $LONG -loop 0 "$LAST" final.gif
