#!/bin/bash
# looks at all the library files, and copies the relevant ones into the source
# folder.

# Change this to the correct path of the libraries.
LIBPATH=~/.lexaloffle/pico-8/carts/alan-pico-lib/

PATHS=$(find $LIBPATH -path '*/src/*.p8' | grep -v demo.p8)

if [ -z $1 ]; then exit; fi

if [ $1 = "update" ]; then
	for path in $PATHS; do
		name=$(echo $path | sed 's/^.*\///g')
		if [ -e src/$name ]; then
			cp -v $path ./$2/src/
		fi
	done
fi

if [ $1 = "view" ]; then
	for path in $PATHS; do
		name=$(echo $path | sed 's/^.*\///g')
		echo $name
	done
fi
