-- this has to go after all the moves, so that the move functions are available in the global scope
|[c_move_funcs]| f_zobj[[
 0,~f_move_splash -- M_STRUGGLE
 ;,~f_move_splash -- M_ACID
  ,~f_move_splash -- M_ACIDARMOR
  ,~f_move_splash -- M_BARRAGE
  ,~f_move_splash -- M_BONECLUB
  ,~f_move_splash -- M_BIND
  ,~f_move_splash -- M_CLAMP
  ,~f_move_splash -- M_MOONLIGHT
  ,~f_move_splash -- M_LEECHSEED
  ,~f_move_splash -- M_EXTREMESPEED
  ,~f_move_splash -- M_SONICBOOM
  ,~f_move_splash -- M_TWINEEDLE
  ,~f_move_splash -- M_THUNDERSHOCK
  ,~f_move_splash -- M_GLARE
  ,~f_move_splash -- M_GUILLOTINE
  ,~f_move_splash -- M_HYPERFANG
  ,~f_move_splash -- M_JUMPKICK
  ,~f_move_splash -- M_KINESIS
  ,~f_move_splash -- M_LOCKON
  ,~f_move_splash -- M_LOVELYKISS
  ,~f_move_splash -- M_MACHPUNCH
  ,~f_move_damage -- M_VICEGRIP
  ,~f_move_splash -- M_SPIKECANNON
  ,~f_move_splash -- M_SPIKES
  ,~f_move_splash -- M_SPORE
  ,~f_move_splash -- M_COTTONSPORE
  ,~f_move_splash -- M_PRESENT
  ,~f_move_splash -- M_VITALTHROW
  ,~f_move_splash -- M_COMETPUNCH
  ,~f_move_damage -- M_DRILLPECK
  ,~f_move_splash -- M_SANDATTACK
  ,~f_move_splash -- M_AGILITY
  ,~f_move_splash -- M_FURYATTACK
  ,~f_move_splash -- M_QUICKATTACK
  ,~f_move_splash -- M_FALSESWIPE
  ,~f_move_splash -- M_GROWL
  ,~f_move_splash -- M_HEALBELL
  ,~f_move_splash -- M_SING
  ,~f_move_damage -- M_POUND
  ,~f_move_splash -- M_MINIMIZE
  ,~f_move_splash -- M_TAILWHIP
  ,~f_move_splash -- M_DOUBLESLAP
  ,~f_move_damage -- M_MEGAHORN
  ,~f_move_splash -- M_BONEMERANG
  ,~f_move_splash -- M_CONVERSION
  ,~f_move_splash -- M_CONVERSION2
  ,~f_move_splash -- M_SPARK
  ,~f_move_splash -- M_MILKDRINK
  ,~f_move_splash -- M_MORNINGSUN
  ,~f_move_splash -- M_NIGHTSHADE
  ,~f_move_splash -- M_OCTAZOOKA
  ,~f_move_splash -- M_PINMISSILE
  ,~f_move_splash -- M_POWDERSNOW
  ,~f_move_splash -- M_SUPERFANG
  ,~f_move_splash -- M_FIRESPIN
  ,~f_move_splash -- M_POISONGAS
  ,~f_move_splash -- M_BARRIER
  ,~f_move_splash -- M_MEDITATE
  ,~f_move_splash -- M_FUTURESIGHT
  ,~f_move_splash -- M_HYPNOSIS
  ,~f_move_splash -- M_PSYBEAM
  ,~f_move_splash -- M_LIGHTSCREEN
  ,~f_move_splash -- M_SAFEGUARD
  ,~f_move_splash -- M_PETALDANCE
  ,~f_move_splash -- M_CHARM
  ,~f_move_splash -- M_SYNTHESIS
  ,~f_move_splash -- M_SWEETSCENT
  ,~f_move_splash -- M_RAZORLEAF
  ,~f_move_splash -- M_POISONPOWDER
  ,~f_move_splash -- M_SLEEPPOWDER
  ,~f_move_splash -- M_ABSORB
  ,~f_move_splash -- M_STUNSPORE
  ,~f_move_splash -- M_FLAIL
  ,~f_move_splash -- M_CONFUSION
  ,~f_move_damage -- M_SLAM
  ,~f_move_splash -- M_CONSTRICT
  ,~f_move_splash -- M_AMNESIA
  ,~f_move_splash -- M_BUBBLE
  ,~f_move_splash -- M_SPLASH
  ,~f_move_damage -- M_HYDROPUMP
  ,~f_move_splash -- M_MINDREADER
  ,~f_move_splash -- M_MIST
  ,~f_move_damage -- M_HORNATTACK
  ,~f_move_splash -- M_SPIDERWEB
  ,~f_move_splash -- M_DOUBLEKICK
  ,~f_move_splash -- M_SWEETKISS
  ,~f_move_splash -- M_METALCLAW
  ,~f_move_splash -- M_TRANSFORM
  ,~f_move_splash -- M_TRIPLEKICK
  ,~f_move_splash -- M_GUST
  ,~f_move_splash -- M_TWISTER
  ,~f_move_splash -- M_CRABHAMMER
  ,~f_move_splash -- M_DIZZYPUNCH
  ,~f_move_splash -- M_SLUDGE
  ,~f_move_splash -- M_PAINSPLIT
  ,~f_move_splash -- M_DESTINYBOND
  ,~f_move_splash -- M_HAZE
  ,~f_move_splash -- M_LICK
  ,~f_move_splash -- M_PERISHSONG
  ,~f_move_splash -- M_MEANLOOK
  ,~f_move_splash -- M_CONFUSERAY
  ,~f_move_splash -- M_CROSSCHOP
  ,~f_move_splash -- M_SMOG
  ,~f_move_splash -- M_KARATECHOP
  ,~f_move_splash -- M_EMBER
  ,~f_move_splash -- M_SMOKESCREEN
  ,~f_move_splash -- M_BELLYDRUM
  ,~f_move_splash -- M_BEATUP
  ,~f_move_damage -- M_SCRATCH
  ,~f_move_splash -- M_SLASH
  ,~f_move_splash -- M_ANCIENTPOWER
  ,~f_move_splash -- M_LEER
  ,~f_move_splash -- M_BITE
  ,~f_move_splash -- M_OUTRAGE
  ,~f_move_splash -- M_SCARYFACE
  ,~f_move_splash -- M_THRASH
  ,~f_move_splash -- M_STOMP
  ,~f_move_splash -- M_ROCKSLIDE
  ,~f_move_splash -- M_MAGNITUDE
  ,~f_move_damage -- M_ROCKTHROW
  ,~f_move_splash -- M_HARDEN
  ,~f_move_splash -- M_BONERUSH
  ,~f_move_splash -- M_HIJUMPKICK
  ,~f_move_splash -- M_RECOVER
  ,~f_move_splash -- M_AEROBLAST
  ,~f_move_splash -- M_HORNDRILL
  ,~f_move_splash -- M_DRAGONRAGE
  ,~f_move_splash -- M_SOFTBOILED
  ,~f_move_splash -- M_DRAGONBREATH
  ,~f_move_splash -- M_SELFDESTRUCT
  ,~f_move_splash -- M_EXPLOSION
  ,~f_move_damage -- M_EGGBOMB
  ,~f_move_splash -- M_SLUDGEBOMB
  ,~f_move_splash -- M_GIGADRAIN
  ,~f_move_splash -- M_MEGADRAIN
  ,~f_move_splash -- M_SWORDSDANCE
  ,~f_move_damage -- M_CUT
  ,~f_move_splash -- M_FURYCUTTER
  ,~f_move_splash -- M_THIEF
  ,~f_move_splash -- M_DIG
  ,~f_move_splash -- M_ROLLOUT
  ,~f_move_splash -- M_DEFENSECURL
  ,~f_move_splash -- M_DETECT
  ,~f_move_splash -- M_SOLARBEAM
  ,~f_move_splash -- M_RAINDANCE
  ,~f_move_splash -- M_FLASH
  ,~f_move_splash -- M_PSYCHIC
  ,~f_move_splash -- M_PSYCHUP
  ,~f_move_splash -- M_DREAMEATER
  ,~f_move_splash -- M_NIGHTMARE
  ,~f_move_splash -- M_SHADOWBALL
  ,~f_move_splash -- M_ZAPCANNON
  ,~f_move_splash -- M_THUNDER
  ,~f_move_splash -- M_THUNDERBOLT
  ,~f_move_splash -- M_IRONTAIL
  ,~f_move_damage -- M_STRENGTH
  ,~f_move_splash -- M_ROCKSMASH
  ,~f_move_splash -- M_HEADBUTT
  ,~f_move_splash -- M_MUDSLAP
  ,~f_move_splash -- M_SUNNYDAY
  ,~f_move_splash -- M_PROTECT
  ,~f_move_splash -- M_DOUBLETEAM
  ,~f_move_splash -- M_SLEEPTALK
  ,~f_move_splash -- M_CURSE
  ,~f_move_splash -- M_HIDDENPOWER
  ,~f_move_splash -- M_SWAGGER
  ,~f_move_splash -- M_FRUSTRATION
  ,~f_move_splash -- M_RETURN
  ,~f_move_splash -- M_TOXIC
  ,~f_move_splash -- M_SNORE
  ,~f_move_splash -- M_REST
  ,~f_move_splash -- M_ENDURE
  ,~f_move_splash -- M_ATTRACT
  ,~f_move_splash -- M_BIDE
  ,~f_move_splash -- M_MIMIC
  ,~f_move_splash -- M_SUBSTITUTE
  ,~f_move_splash -- M_RAGE
  ,~f_move_splash -- M_DOUBLEEDGE
  ,~f_move_splash -- M_TAKEDOWN
  ,~f_move_splash -- M_SKULLBASH
  ,~f_move_splash -- M_BODYSLAM
  ,~f_move_damage -- M_WATERGUN
  ,~f_move_splash -- M_BUBBLEBEAM
  ,~f_move_splash -- M_ICEBEAM
  ,~f_move_splash -- M_BLIZZARD
  ,~f_move_splash -- M_ICYWIND
  ,~f_move_damage -- M_SURF
  ,~f_move_splash -- M_WHIRLPOOL
  ,~f_move_damage -- M_WATERFALL
  ,~f_move_splash -- M_SWIFT
  ,~f_move_damage -- M_PAYDAY
  ,~f_move_splash -- M_TRIATTACK
  ,~f_move_splash -- M_REFLECT
  ,~f_move_splash -- M_THUNDERWAVE
  ,~f_move_splash -- M_TELEPORT
  ,~f_move_splash -- M_PSYWAVE
  ,~f_move_splash -- M_METRONOME
  ,~f_move_splash -- M_COUNTER
  ,~f_move_damage -- M_MEGAPUNCH
  ,~f_move_splash -- M_SEISMICTOSS
  ,~f_move_splash -- M_SUBMISSION
  ,~f_move_damage -- M_MEGAKICK
  ,~f_move_splash -- M_DYNAMICPUNCH
  ,~f_move_splash -- M_FIREPUNCH
  ,~f_move_splash -- M_THUNDERPUNCH
  ,~f_move_splash -- M_ICEPUNCH
  ,~f_move_splash -- M_FIREBLAST
  ,~f_move_splash -- M_FLAMETHROWER
  ,~f_move_splash -- M_FISSURE
  ,~f_move_splash -- M_EARTHQUAKE
  ,~f_move_splash -- M_SANDSTORM
  ,~f_move_splash -- M_HYPERBEAM
  ,~f_move_splash -- M_ROAR
  ,~f_move_splash -- M_STEELWING
  ,~f_move_splash -- M_FLY
  ,~f_move_splash -- M_RAZORWIND
  ,~f_move_splash -- M_WHIRLWIND
  ,~f_move_splash -- M_SKYATTACK
  ,~f_move_damage -- M_WINGATTACK
  ,~f_move_damage -- M_PECK
  ,~f_move_splash -- M_MIRRORMOVE
  ,~f_move_splash -- M_FAINTATTACK
  ,~f_move_splash -- M_WITHDRAW
  ,~f_move_splash -- M_RAPIDSPIN
  ,~f_move_splash -- M_SUPERSONIC
  ,~f_move_splash -- M_AURORABEAM
  ,~f_move_splash -- M_MIRRORCOAT
  ,~f_move_splash -- M_POISONSTING
  ,~f_move_splash -- M_SPITE
  ,~f_move_splash -- M_CRUNCH
  ,~f_move_splash -- M_PURSUIT
  ,~f_move_splash -- M_STRINGSHOT
  ,~f_move_splash -- M_LEECHLIFE
  ,~f_move_splash -- M_BATONPASS
  ,~f_move_splash -- M_DISABLE
  ,~f_move_splash -- M_SCREECH
  ,~f_move_damage -- M_TACKLE
  ,~f_move_splash -- M_FLAMEWHEEL
  ,~f_move_splash -- M_REVERSAL
  ,~f_move_splash -- M_FURYSWIPES
  ,~f_move_splash -- M_FOCUSENERGY
  ,~f_move_splash -- M_FORESIGHT
  ,~f_move_splash -- M_LOWKICK
  ,~f_move_splash -- M_ROLLINGKICK
  ,~f_move_splash -- M_ENCORE
  ,~f_move_splash -- M_WRAP
  ,~f_move_splash -- M_GROWTH
  ,~f_move_damage -- M_VINEWHIP
  ,~f_move_splash -- M_SACREDFIRE
  ,~f_move_splash -- M_SHARPEN
  ,~f_move_splash -- M_SKETCH
  ,~f_move_splash -- M_TM05
  ,~f_move_splash -- M_NONE
]] $$
