#!/usr/bin/env python3

import sys
var_mappings={}
for x in sys.argv[1:]:
    keyvalue = x.split(":", 1)
    var_mappings[keyvalue[0]] = "" if len(keyvalue) == 1 else keyvalue[1]

for line in (line.rstrip("\n") for line in sys.stdin):
    for k, v in var_mappings.items():
        line = line.replace(k, v)
    print(line)
