#!/usr/bin/env bash

inotifywait -e close_write,moved_to,create -mr ./src |
while read -r directory; do
  echo "** '$directory' was changed, so let's compile this thing!"
  "./pico-compile" "$@"
  echo
done
