#!/bin/bash
mkdir -p build
cp game.p8 build/outline.p8
perl -0777 -pi -e '
my $doc = do {
    local $/ = undef;
    open my $fh, "<", "compile_outline.lua"
        or die "could not open file";
    <$fh>;
}; my $header = "'"-- $t1\n-- $t2"'";
s/(__lua__).*(__gfx__)/$1\n$header\n$doc\n$2/igs;
' build/outline.p8

pico8 -x build/outline > src/01-outlines.lua
sed -i '/RUNNING/d' src/01-outlines.lua
rm build/outline.p8
