-- fade should be a table (generated by gen_fade)
-- val is between -1 and 1
function fade(f, val)
	wid = #f[1] - 1
	val = min(max(flr(wid - abs(val) * wid), 0), wid) + 1

	for c=0,15 do
		pal(c,f[c+1][val])
	end
end
