#!/bin/bash
echo "GENERATING SUB IMAGES..."
pico8 -screenshot_scale 3 -x preview.lua -p shot
echo

echo "CREATING ROWS..."
for i in 0 4 8 12 16 20 24; do
  convert +append \
    "$HOME/Desktop/col-$((i+0)).png" \
    "$HOME/Desktop/col-$((i+1)).png" \
    "$HOME/Desktop/col-$((i+2)).png" \
    "$HOME/Desktop/col-$((i+3)).png" \
    "$HOME/Desktop/row-$((i/4)).png"
    # "$HOME/Desktop/bw-$((i+0)).png" \
    # "$HOME/Desktop/bw-$((i+1)).png" \
    # "$HOME/Desktop/bw-$((i+2)).png" \
    # "$HOME/Desktop/bw-$((i+3)).png" \
done


echo "COMBINING ALL ROWS..."
convert -append $(seq 0  6  | awk "{print \"$HOME/Desktop/row-\" \$1 \".png\"}") "$HOME/Desktop/all.png"
echo

echo "COPYING TO CLIPBOARD..."
cat "$HOME/Desktop/all.png" | ccl >/dev/null
echo

echo "DONE"
