function init() -- entry point for this compile script
  for trainer in all(datastr_to_arr(g_trainer_data)) do
    for thing in all(trainer) do
      offsetpoke(thing)
    end
  end
  log("Wrote Trainer Data")
end

-- 60 trainers total - doesn't include missingno, i think you should unlock that a different way (horde mode again?)
g_trainer_data = [[
  P_RATTATA    P_PIDGEY     P_WOOPER     P_SENTRET    P_ZUBAT      P_EEVEE      I_BERRY             M_SWIFT        -- youngster    TM39
  P_PSYDUCK    P_CUBONE     P_HOOTHOOT   P_MEOWTH     P_GASTLY     P_BELLSPROUT I_THICKCLUB         M_DREAMEATER   -- sage         TM42
  P_PIDGEY     P_DELIBIRD   P_SPEAROW    P_FARFETCHD  P_DODUO      P_PIDGEOTTO  I_STICK             M_MUDSLAP      -- falkner      TM31

  P_ZUBAT      P_EKANS      P_GRIMER     P_SLOWPOKE   P_KOFFING    P_RATICATE   I_POISONCUREBERRY   M_FRUSTRATION  -- rocketgrunt  TM21
  P_CATERPIE   P_LEDYBA     P_PARAS      P_WEEDLE     P_VENONAT    P_SPINARAK   I_PARALYZECUREBERRY M_CUT          -- bugcatcher   HM01
  P_KAKUNA     P_WEEPINBELL P_METAPOD    P_PINSIR     P_PINECO     P_SCYTHER    I_SILVERPOWDER      M_FURYCUTTER   -- bugsy        TM49

  P_CYNDAQUIL  P_TOTODILE   P_IGGLYBUFF  P_PICHU      P_CHIKORITA  P_SNUBBULL   I_BITTERBERRY       M_RETURN       -- pokefan      TM27
  P_MAREEP     P_POLIWAG    P_TEDDIURSA  P_CLEFFA     P_HOPPIP     P_TOGEPI     I_MYSTERYBERRY      M_PSYCHUP      -- beauty       TM09
  P_JIGGLYPUFF P_CLEFAIRY   P_CHANSEY    P_PHANPY     P_LICKITUNG  P_MILTANK    I_PINKBOW           M_ATTRACT      -- whitney      TM45

  P_EEVEE      P_VAPOREON   P_JOLTEON    P_FLAREON    P_ESPEON     P_UMBREON    I_MYSTERYBERRY      M_REST         -- kiminogirl   TM44
  P_CUBONE     P_GASTLY     P_ABRA       P_DROWZEE    P_HAUNTER    P_SLOWBRO    I_BITTERBERRY       M_NIGHTMARE    -- medium       TM50
  P_WOBBUFFET  P_STANTLER   P_HAUNTER    P_MISDREAVUS P_SUDOWOODO  P_GENGAR     I_SPELLTAG          M_SHADOWBALL   -- morty        TM30

  P_LARVITAR   P_NIDORANF   P_HOUNDOUR   P_VULPIX     P_NIDORANM   P_GROWLITHE  I_BURNTBERRY        M_ROAR         -- officer      TM05
  P_MACHOP     P_TYROGUE    P_MANKEY     P_POLIWHIRL  P_ONIX       P_HERACROSS  I_BLACKBELT         M_ROCKSMASH    -- blackbelt    TM08
  P_MACHOKE    P_GRANBULL   P_HITMONTOP  P_POLITOED   P_PRIMEAPE   P_POLIWRATH  I_KINGSROCK         M_DYNAMICPUNCH -- chuck        TM01

  P_CROCONAW   P_FLAAFFY    P_QUILAVA    P_PIKACHU    P_BAYLEEF    P_NOCTOWL    I_LIGHTBALL         M_FLY          -- gentleman    HM02
  P_HORSEA     P_MARILL     P_MACHOKE    P_KRABBY     P_GEODUDE    P_QUAGSIRE   I_PARALYZECUREBERRY M_STRENGTH     -- sailor       HM04
  P_CORSOLA    P_MAGNEMITE  P_FORRETRESS P_SKARMORY   P_MANTINE    P_STEELIX    I_METALCOAT         M_IRONTAIL     -- jasmine      TM23

  P_ARBOK      P_RATICATE   P_GOLBAT     P_MURKROW    P_WEEZING    P_PERSIAN    I_AMULETCOIN        M_HEADBUTT     -- rocketexec   TM02
  P_SMOOCHUM   P_SHELLDER   P_SWINUB     P_DELIBIRD   P_SEEL       P_AZUMARILL  I_ICEBERRY          M_ICEPUNCH     -- skier        TM33
  P_LAPRAS     P_FEAROW     P_SNEASEL    P_URSARING   P_DEWGONG    P_PILOSWINE  I_NEVERMELTICE      M_ICYWIND      -- pryce        TM16

  P_VOLTORB    P_PORYGON    P_KOFFING    P_SMEARGLE   P_ODDISH     P_DITTO      I_METALPOWDER       M_THUNDER      -- scientist    TM25
  P_SHUCKLE    P_DRATINI    P_MAGIKARP   P_SKIPLOOM   P_SEADRA     P_LEDIAN     I_MINTBERRY         M_SWEETSCENT   -- twins        TM12
  P_DONPHAN    P_DRAGONAIR  P_AMPHAROS   P_GYARADOS   P_PUPITAR    P_KINGDRA    I_DRAGONFANG        M_DRAGONBREATH -- clair        TM24

  P_ELEKID     P_OMANYTE    P_TENTACOOL  P_KABUTO     P_PONYTA     P_GLIGAR     I_SCOPELENS         M_CURSE        -- supernerd    TM03
  P_DIGLETT    P_NIDORINA   P_SANDSHREW  P_PRIMEAPE   P_GRAVELER   P_NIDORINO   I_POISONCUREBERRY   M_DEFENSECURL  -- camper       TM40
  P_OMASTAR    P_RHYHORN    P_KABUTOPS   P_AERODACTYL P_STEELIX    P_GOLEM      I_HARDSTONE         M_SANDSTORM    -- brock        TM37

  P_NATU       P_YANMA      P_DITTO      P_LEDIAN     P_TANGELA    P_TOGETIC    I_ICEBERRY          M_ROLLOUT      -- schoolboy    TM04
  P_STARYU     P_MANTINE    P_REMORAID   P_QWILFISH   P_GOLDEEN    P_TENTACRUEL I_GOLDBERRY         M_WHIRLPOOL    -- swimmer      HM06
  P_GOLDUCK    P_QUAGSIRE   P_WIGGLYTUFF P_BLASTOISE  P_SEAKING    P_STARMIE    I_MYSTICWATER       M_SURF         -- misty        HM03

  P_CHARMANDER P_SUNKERN    P_SQUIRTLE   P_OMASTAR    P_BULBASAUR  P_UNOWN      I_BERRY             M_HIDDENPOWER  -- juggler      TM10
  P_KABUTOPS   P_CHINCHOU   P_ARBOK      P_SCIZOR     P_SANDSLASH  P_ELECTABUZZ I_BERSERKGENE       M_FLASH        -- guitarist    HM05
  P_MAGNETON   P_ELECTRODE  P_PORYGON2   P_LANTURN    P_ELECTABUZZ P_RAICHU     I_MAGNET            M_ZAPCANNON    -- ltsurge      TM07

  P_SANDSLASH  P_GLIGAR     P_PARASECT   P_MAROWAK    P_DONPHAN    P_DUGTRIO    I_SOFTSAND          M_DIG          -- hiker        TM28
  P_BUTTERFREE P_GRANBULL   P_GLOOM      P_WIGGLYTUFF P_SUNFLORA   P_CLEFABLE   I_POLKADOTBOW       M_SOLARBEAM    -- lass         TM22
  P_TANGELA    P_MEGANIUM   P_VILEPLUME  P_BELLOSSOM  P_PARASECT   P_VICTREEBEL I_MIRACLESEED       M_GIGADRAIN    -- erika        TM19

  P_SMEARGLE   P_SLUGMA     P_PINSIR     P_TAUROS     P_TENTACRUEL P_RAPIDASH   I_CHARCOAL          M_FIREPUNCH    -- biker        TM48
  P_EXEGGCUTE  P_AZUMARILL  P_FURRET     P_CLEFABLE   P_JUMPLUFF   P_KANGASKHAN I_MIRACLEBERRY      M_SLEEPTALK    -- picnicker    TM35
  P_WEEZING    P_ARIADOS    P_ELECTRODE  P_MUK        P_NIDORINA   P_VENOMOTH   I_POISONBARB        M_SLUDGEBOMB   -- janine       TM36

  P_WARTORTLE  P_MAGNEMITE  P_IVYSAUR    P_KANGASKHAN P_CHARMELEON P_DODRIO     I_BERSERKGENE       M_SNORE        -- pokemaniac   TM13
  P_MRMIME     P_GIRAFARIG  P_WOBBUFFET  P_KADABRA    P_SLOWBRO    P_HYPNO      I_MINTBERRY         M_THUNDERPUNCH -- psychic      TM41
  P_KADABRA    P_JYNX       P_STARMIE    P_HYPNO      P_MRMIME     P_ALAKAZAM   I_TWISTEDSPOON      M_PSYCHIC      -- sabrina      TM29

  P_QWILFISH   P_DUNSPARCE  P_CLOYSTER   P_SEAKING    P_CORSOLA    P_KINGLER    I_MYSTICWATER       M_WATERFALL    -- fisher       HM07
  P_PERSIAN    P_MAGCARGO   P_RAPIDASH   P_BEEDRILL   P_MAGBY      P_NINETALES  I_BURNTBERRY        M_SUNNYDAY     -- firebreather TM11
  P_ARCANINE   P_GOLEM      P_TYPHLOSION P_MAGCARGO   P_OCTILLERY  P_MAGMAR     I_CHARCOAL          M_FIREBLAST    -- blaine       TM38

  P_FEAROW     P_DODUO      P_PIDGEOTTO  P_NOCTOWL    P_DODRIO     P_PIDGEOT    I_SHARPBEAK         M_STEELWING    -- birdkeeper   TM47
  P_AIPOM      P_DUGTRIO    P_DEWGONG    P_CHANSEY    P_FERALIGATR P_BLISSEY    I_LUCKYPUNCH        M_RAINDANCE    -- cooltrainer  TM18
  P_PIDGEOT    P_ARCANINE   P_NIDOQUEEN  P_NIDOKING   P_VAPOREON   P_RHYDON     I_SOFTSAND          M_EARTHQUAKE   -- blue         TM26

  P_CROBAT     P_MAGNETON   P_URSARING   P_SNEASEL    P_GENGAR     P_TYRANITAR  I_QUICKCLAW         M_PROTECT      -- silver       TM17
  P_GIRAFARIG  P_LAPRAS     P_EXEGGUTOR  P_SLOWKING   P_JYNX       P_XATU       I_TWISTEDSPOON      M_BLIZZARD     -- will         TM14
  P_MUK        P_FORRETRESS P_VENOMOTH   P_ARIADOS    P_NIDOKING   P_CROBAT     I_POISONBARB        M_TOXIC        -- koga         TM06

  P_HITMONCHAN P_HITMONLEE  P_POLIWRATH  P_HERACROSS  P_HITMONTOP  P_MACHAMP    I_FOCUSBAND         M_DETECT       -- bruno        TM43
  P_MISDREAVUS P_MURKROW    P_VENUSAUR   P_UMBREON    P_VILEPLUME  P_HOUNDOOM   I_BLACKGLASSES      M_THIEF        -- karen        TM46
  P_AERODACTYL P_GYARADOS   P_SNORLAX    P_KINGDRA    P_CHARIZARD  P_DRAGONITE  I_DRAGONFANG        M_HYPERBEAM    -- lance        TM15

  P_RAIKOU     P_TYRANITAR  P_ENTEI      P_CELEBI     P_SUICUNE    P_HOOH       I_BRIGHTPOWDER      M_SWAGGER      -- eusine       TM34
  P_ARTICUNO   P_DRAGONITE  P_ZAPDOS     P_MEW        P_MOLTRES    P_LUGIA      I_BRIGHTPOWDER      M_ENDURE       -- lawrence     TM20
  P_CLOYSTER   P_EXEGGUTOR  P_MAROWAK    P_SNORLAX    P_SKARMORY   P_MEWTWO     I_LEFTOVERS         M_DOUBLETEAM   -- red          TM32
]]
