function init() -- entry point for this compile script
  for trainer in all(datastr_to_arr(g_trainer_data)) do
    for thing in all(trainer) do
      offsetpoke(thing)
    end
  end
  log("Wrote Trainer Data")
end

-- I_BRIGHTPOWDER I_FOCUSBAND       I_KINGSROCK   I_LEFTOVERS  I_QUICKCLAW         I_SCOPELENS   I_SILVERPOWDER I_BLACKGLASSES
-- I_DRAGONFANG   I_MAGNET          I_BLACKBELT   I_CHARCOAL   I_SHARPBEAK         I_SPELLTAG    I_MIRACLESEED  I_SOFTSAND
-- I_NEVERMELTICE I_PINKBOW         I_POLKADOTBOW I_POISONBARB I_TWISTEDSPOON      I_HARDSTONE   I_METALCOAT    I_MYSTICWATER
-- I_STICK        I_THICKCLUB       I_LIGHTBALL   I_LUCKYPUNCH I_METALPOWDER
-- I_AMULETCOIN   I_MIRACLEBERRY    I_GOLDBERRY   I_BERSERKGENE

-- I_BERRY
-- I_POISONCUREBERRY
-- I_ICEBERRY
-- I_BURNTBERRY
--                                                                                                             I_PARALYZECUREBERRY
--                                                                                                             I_BITTERBERRY
--                                                                                                             I_MYSTERYBERRY
--                                                                                                             I_MINTBERRY

-- 60 trainers total - doesn't include missingno, i think you should unlock that a different way (horde mode again?)
g_trainer_data = [[
  M_CUT          P_RATTATA    P_PIDGEY     P_WOOPER     P_SENTRET    P_ZUBAT      P_EEVEE      -- youngster    I_BERRY
  M_HYPNOSIS     P_PSYDUCK    P_HOOTHOOT   P_MEOWTH     P_CUBONE     P_BELLSPROUT P_GASTLY     -- sage         I_THICKCLUB
  M_MUDSLAP      P_PIDGEY     P_DELIBIRD   P_SPEAROW    P_FARFETCHD  P_DODUO      P_PIDGEOTTO  -- falkner      I_STICK

  M_FRUSTRATION  P_ZUBAT      P_EKANS      P_GRIMER     P_SLOWPOKE   P_KOFFING    P_RATICATE   -- rocketgrunt  I_POISONCUREBERRY
  M_DISABLE      P_CATERPIE   P_LEDYBA     P_PARAS      P_WEEDLE     P_VENONAT    P_SPINARAK   -- bugcatcher   I_PARALYZECUREBERRY
  M_FURYCUTTER   P_KAKUNA     P_WEEPINBELL P_METAPOD    P_PINSIR     P_PINECO     P_SCYTHER    -- bugsy        I_SILVERPOWDER

  M_RETURN       P_CYNDAQUIL  P_TOTODILE   P_IGGLYBUFF  P_PICHU      P_CHIKORITA  P_SNUBBULL   -- pokefan      I_BITTERBERRY
  M_METRONOME    P_MAREEP     P_POLIWAG    P_TEDDIURSA  P_CLEFFA     P_HOPPIP     P_TOGEPI     -- beauty       I_MYSTERYBERRY
  M_ATTRACT      P_JIGGLYPUFF P_CLEFAIRY   P_CHANSEY    P_PHANPY     P_LICKITUNG  P_MILTANK    -- whitney      I_PINKBOW

  M_FOCUSENERGY  P_EEVEE      P_VAPOREON   P_JOLTEON    P_FLAREON    P_ESPEON     P_UMBREON    -- kiminogirl   I_MYSTERYBERRY
  M_CURSE        P_CUBONE     P_GASTLY     P_ABRA       P_DROWZEE    P_HAUNTER    P_SLOWBRO    -- medium       I_BITTERBERRY
  M_SHADOWBALL   P_WOBBUFFET  P_STANTLER   P_HAUNTER    P_MISDREAVUS P_SUDOWOODO  P_GENGAR     -- morty        I_SPELLTAG

  M_CRUNCH       P_LARVITAR   P_NIDORANF   P_HOUNDOUR   P_VULPIX     P_NIDORANM   P_GROWLITHE  -- officer      I_BURNTBERRY
  M_REVERSAL     P_MACHOP     P_TYROGUE    P_MANKEY     P_POLIWHIRL  P_ONIX       P_HERACROSS  -- blackbelt    I_BLACKBELT
  M_DYNAMICPUNCH P_MACHOKE    P_GRANBULL   P_HITMONTOP  P_POLITOED   P_PRIMEAPE   P_POLIWRATH  -- chuck        I_KINGSROCK

  M_HYPNOSIS     P_CROCONAW   P_FLAAFFY    P_QUILAVA    P_PIKACHU    P_BAYLEEF    P_NOCTOWL    -- gentleman    I_LIGHTBALL
  M_ROLLOUT      P_HORSEA     P_MARILL     P_MACHOKE    P_KRABBY     P_GEODUDE    P_QUAGSIRE   -- sailor       I_PARALYZECUREBERRY
  M_IRONTAIL     P_CORSOLA    P_MAGNEMITE  P_FORRETRESS P_SKARMORY   P_MANTINE    P_STEELIX    -- jasmine      I_METALCOAT

  M_SPITE        P_ARBOK      P_RATICATE   P_GOLBAT     P_MURKROW    P_WEEZING    P_PERSIAN    -- rocketexec   I_AMULETCOIN
  M_BLIZZARD     P_SMOOCHUM   P_SHELLDER   P_SWINUB     P_DELIBIRD   P_SEEL       P_AZUMARILL  -- skier        I_ICEBERRY
  M_ICYWIND      P_LAPRAS     P_FEAROW     P_SNEASEL    P_URSARING   P_DEWGONG    P_PILOSWINE  -- pryce        I_NEVERMELTICE

  M_PROTECT      P_VOLTORB    P_PORYGON    P_KOFFING    P_SMEARGLE   P_ODDISH     P_DITTO      -- scientist    I_METALPOWDER
  M_PSYBEAM      P_SHUCKLE    P_DRATINI    P_MAGIKARP   P_SKIPLOOM   P_SEADRA     P_LEDIAN     -- twins        I_MINTBERRY
  M_DRAGONBREATH P_DONPHAN    P_DRAGONAIR  P_AMPHAROS   P_GYARADOS   P_PUPITAR    P_KINGDRA    -- clair        I_DRAGONFANG

  M_HEADBUTT     P_ELEKID     P_OMANYTE    P_TENTACOOL  P_KABUTO     P_PONYTA     P_GLIGAR     -- supernerd    I_SCOPELENS
  M_ICEBEAM      P_DIGLETT    P_NIDORINA   P_SANDSHREW  P_PRIMEAPE   P_GRAVELER   P_NIDORINO   -- camper       I_POISONCUREBERRY
  M_SANDSTORM    P_OMASTAR    P_RHYHORN    P_KABUTOPS   P_AERODACTYL P_STEELIX    P_GOLEM      -- brock        I_HARDSTONE

  M_METRONOME    P_NATU       P_YANMA      P_DITTO      P_LEDIAN     P_TANGELA    P_TOGETIC    -- schoolboy    I_ICEBERRY
  M_RAINDANCE    P_STARYU     P_MANTINE    P_REMORAID   P_QWILFISH   P_GOLDEEN    P_TENTACRUEL -- swimmer      I_GOLDBERRY
  M_SURF         P_GOLDUCK    P_QUAGSIRE   P_WIGGLYTUFF P_BLASTOISE  P_SEAKING    P_STARMIE    -- misty        I_MYSTICWATER

  M_THUNDERBOLT  P_CHARMANDER P_SUNKERN    P_SQUIRTLE   P_OMASTAR    P_BULBASAUR  P_UNOWN      -- juggler      I_BERRY
  M_ENDURE       P_KABUTOPS   P_CHINCHOU   P_ARBOK      P_SCIZOR     P_SANDSLASH  P_ELECTABUZZ -- guitarist    I_BERSERKGENE
  M_ZAPCANNON    P_MAGNETON   P_ELECTRODE  P_PORYGON2   P_LANTURN    P_ELECTABUZZ P_RAICHU     -- ltsurge      I_MAGNET

  M_DIG          P_SANDSLASH  P_GLIGAR     P_PARASECT   P_MAROWAK    P_DONPHAN    P_DUGTRIO    -- hiker        I_SOFTSAND
  M_SUNNYDAY     P_BUTTERFREE P_GRANBULL   P_GLOOM      P_WIGGLYTUFF P_SUNFLORA   P_CLEFABLE   -- lass         I_POLKADOTBOW
  M_GIGADRAIN    P_TANGELA    P_MEGANIUM   P_VILEPLUME  P_BELLOSSOM  P_PARASECT   P_VICTREEBEL -- erika        I_MIRACLESEED

  M_FLAMETHROWER P_SMEARGLE   P_SLUGMA     P_PINSIR     P_TAUROS     P_TENTACRUEL P_RAPIDASH   -- biker        I_CHARCOAL
  M_ROAR         P_FURRET     P_EXEGGCUTE  P_AZUMARILL  P_CLEFABLE   P_JUMPLUFF   P_KANGASKHAN -- picnicker    I_MIRACLEBERRY
  M_TOXIC        P_WEEZING    P_ARIADOS    P_ELECTRODE  P_MUK        P_NIDORINA   P_VENOMOTH   -- janine       I_POISONBARB

  M_THUNDERBOLT  P_WARTORTLE  P_MAGNEMITE  P_IVYSAUR    P_KANGASKHAN P_CHARMELEON P_DODRIO     -- pokemaniac   I_BERSERKGENE
  M_REST         P_MRMIME     P_GIRAFARIG  P_WOBBUFFET  P_KADABRA    P_SLOWBRO    P_HYPNO      -- psychic      I_MINTBERRY
  M_PSYCHIC      P_KADABRA    P_JYNX       P_STARMIE    P_HYPNO      P_MRMIME     P_ALAKAZAM   -- sabrina      I_TWISTEDSPOON

  M_WHIRLPOOL    P_QWILFISH   P_DUNSPARCE  P_CLOYSTER   P_SEAKING    P_CORSOLA    P_KINGLER    -- fisher       I_MYSTICWATER
  M_FLAMETHROWER P_PERSIAN    P_MAGCARGO   P_RAPIDASH   P_BEEDRILL   P_MAGBY      P_NINETALES  -- firebreather I_BURNTBERRY
  M_FIREBLAST    P_ARCANINE   P_GOLEM      P_TYPHLOSION P_MAGCARGO   P_OCTILLERY  P_MAGMAR     -- blaine       I_CHARCOAL

  M_SKYATTACK    P_FEAROW     P_DODUO      P_PIDGEOTTO  P_NOCTOWL    P_DODRIO     P_PIDGEOT    -- birdkeeper   I_SHARPBEAK
  M_MINIMIZE     P_DEWGONG    P_AIPOM      P_DUGTRIO    P_CHANSEY    P_FERALIGATR P_BLISSEY    -- cooltrainer  I_LUCKYPUNCH
  M_EARTHQUAKE   P_PIDGEOT    P_ARCANINE   P_NIDOQUEEN  P_NIDOKING   P_VAPOREON   P_RHYDON     -- blue         I_SOFTSAND

  M_CRUNCH       P_CROBAT     P_MAGNETON   P_URSARING   P_SNEASEL    P_GENGAR     P_TYRANITAR  -- silver       I_QUICKCLAW
  M_ICEBEAM      P_GIRAFARIG  P_LAPRAS     P_EXEGGUTOR  P_SLOWKING   P_JYNX       P_XATU       -- will         I_TWISTEDSPOON
  M_TOXIC        P_MUK        P_FORRETRESS P_VENOMOTH   P_ARIADOS    P_NIDOKING   P_CROBAT     -- koga         I_POISONBARB

  M_FOCUSENERGY  P_HITMONCHAN P_HITMONLEE  P_POLIWRATH  P_HERACROSS  P_HITMONTOP  P_MACHAMP    -- bruno        I_FOCUSBAND
  M_MUDSLAP      P_MISDREAVUS P_MURKROW    P_VENUSAUR   P_UMBREON    P_VILEPLUME  P_HOUNDOOM   -- karen        I_BLACKGLASSES
  M_DRAGONBREATH P_AERODACTYL P_GYARADOS   P_SNORLAX    P_KINGDRA    P_CHARIZARD  P_DRAGONITE  -- lance        I_DRAGONFANG

                 P_RAIKOU     P_TYRANITAR  P_ENTEI      P_CELEBI     P_SUICUNE    P_HOOH       -- Eusine       I_BRIGHTPOWDER
                 P_ARTICUNO   P_DRAGONITE  P_ZAPDOS     P_MEW        P_MOLTRES    P_LUGIA      -- Lawrence     I_BRIGHTPOWDER
  M_FLAMETHROWER P_CLOYSTER   P_EXEGGUTOR  P_MAROWAK    P_SKARMORY   P_SNORLAX    P_MEWTWO     -- red          I_LEFTOVERS
]]
