#!/bin/sh
# convert all moves (from pokeapi) into numbers.

sed 's/high-jump-kick/145/g' |
sed 's/thunder-shock/114/g' |
sed 's/poison-powder/108/g' |
sed 's/thunder-punch/62/g' |
sed 's/spike-cannon/141/g' |
sed 's/sleep-powder/110/g' |
sed 's/self-destruct/36/g' |
sed 's/quick-attack/120/g' |
sed 's/light-screen/131/g' |
sed 's/focus-energy/133/g' |
sed 's/defense-curl/129/g' |
sed 's/thunder-wave/45/g' |
sed 's/string-shot/112/g' |
sed 's/smokescreen/126/g' |
sed 's/seismic-toss/19/g' |
sed 's/rolling-kick/74/g' |
sed 's/poison-sting/83/g' |
sed 's/petal-dance/111/g' |
sed 's/night-shade/121/g' |
sed 's/mirror-move/134/g' |
sed 's/lovely-kiss/150/g' |
sed 's/fury-swipes/158/g' |
sed 's/flamethrower/96/g' |
sed 's/dizzy-punch/153/g' |
sed 's/confuse-ray/127/g' |
sed 's/aurora-beam/100/g' |
sed 's/wing-attack/67/g' |
sed 's/thunderbolt/24/g' |
sed 's/swords-dance/3/g' |
sed 's/super-fang/163/g' |
sed 's/stun-spore/109/g' |
sed 's/soft-boiled/41/g' |
sed 's/sand-attack/75/g' |
sed 's/rock-throw/115/g' |
sed 's/razor-leaf/107/g' |
sed 's/poison-gas/147/g' |
sed 's/pin-missile/85/g' |
sed 's/leech-seed/105/g' |
sed 's/leech-life/149/g' |
sed 's/karate-chop/57/g' |
sed 's/hyper-fang/160/g' |
sed 's/horn-attack/77/g' |
sed 's/fury-attack/78/g' |
sed 's/drill-peck/102/g' |
sed 's/dream-eater/42/g' |
sed 's/dragon-rage/23/g' |
sed 's/double-team/32/g' |
sed 's/double-slap/58/g' |
sed 's/double-kick/72/g' |
sed 's/double-edge/10/g' |
sed 's/crabhammer/157/g' |
sed 's/conversion/162/g' |
sed 's/comet-punch/59/g' |
sed 's/bubble-beam/11/g' |
sed 's/bonemerang/159/g' |
sed 's/acid-armor/156/g' |
sed 's/waterfall/139/g' |
sed 's/tri-attack/49/g' |
sed 's/transform/151/g' |
sed 's/supersonic/91/g' |
sed 's/substitute/50/g' |
sed 's/submission/17/g' |
sed 's/sonic-boom/92/g' |
sed 's/solar-beam/22/g' |
sed 's/sky-attack/43/g' |
sed 's/skull-bash/40/g' |
sed 's/rock-slide/48/g' |
sed 's/mega-drain/21/g' |
sed 's/hyper-beam/15/g' |
sed 's/hydro-pump/98/g' |
sed 's/guillotine/65/g' |
sed 's/fire-spin/113/g' |
sed 's/fire-punch/60/g' |
sed 's/fire-blast/38/g' |
sed 's/earthquake/26/g' |
sed 's/constrict/142/g' |
sed 's/confusion/116/g' |
sed 's/bone-club/138/g' |
sed 's/withdraw/128/g' |
sed 's/water-gun/12/g' |
sed 's/vine-whip/70/g' |
sed 's/vice-grip/64/g' |
sed 's/twineedle/84/g' |
sed 's/tail-whip/82/g' |
sed 's/razor-wind/2/g' |
sed 's/minimize/125/g' |
sed 's/metronome/35/g' |
sed 's/mega-punch/1/g' |
sed 's/meditate/118/g' |
sed 's/low-kick/103/g' |
sed 's/jump-kick/73/g' |
sed 's/ice-punch/61/g' |
sed 's/hypnosis/117/g' |
sed 's/horn-drill/7/g' |
sed 's/explosion/47/g' |
sed 's/whirlwind/4/g' |
sed 's/teleport/30/g' |
sed 's/take-down/9/g' |
sed 's/strength/54/g' |
sed 's/sharpen/161/g' |
sed 's/screech/122/g' |
sed 's/recover/123/g' |
sed 's/mega-kick/5/g' |
sed 's/kinesis/144/g' |
sed 's/ice-beam/13/g' |
sed 's/headbutt/76/g' |
sed 's/egg-bomb/37/g' |
sed 's/body-slam/8/g' |
sed 's/blizzard/14/g' |
sed 's/barrier/130/g' |
sed 's/barrage/148/g' |
sed 's/amnesia/143/g' |
sed 's/agility/119/g' |
sed 's/thunder/25/g' |
sed 's/struggle/0/g' |
sed 's/splash/155/g' |
sed 's/sludge/137/g' |
sed 's/scratch/63/g' |
sed 's/reflect/33/g' |
sed 's/psywave/46/g' |
sed 's/psychic/29/g' |
sed 's/psybeam/99/g' |
sed 's/pay-day/16/g' |
sed 's/harden/124/g' |
sed 's/growth/106/g' |
sed 's/fissure/27/g' |
sed 's/disable/93/g' |
sed 's/counter/18/g' |
sed 's/bubble/152/g' |
sed 's/absorb/104/g' |
sed 's/thrash/81/g' |
sed 's/tackle/79/g' |
sed 's/spore/154/g' |
sed 's/slash/164/g' |
sed 's/glare/146/g' |
sed 's/clamp/140/g' |
sed 's/swift/39/g' |
sed 's/stomp/71/g' |
sed 's/smog/136/g' |
sed 's/pound/56/g' |
sed 's/peck/101/g' |
sed 's/mimic/31/g' |
sed 's/lick/135/g' |
sed 's/haze/132/g' |
sed 's/growl/88/g' |
sed 's/flash/55/g' |
sed 's/ember/95/g' |
sed 's/wrap/80/g' |
sed 's/toxic/6/g' |
sed 's/surf/53/g' |
sed 's/slam/69/g' |
sed 's/sing/90/g' |
sed 's/roar/89/g' |
sed 's/rest/44/g' |
sed 's/rage/20/g' |
sed 's/mist/97/g' |
sed 's/leer/86/g' |
sed 's/gust/66/g' |
sed 's/bite/87/g' |
sed 's/bind/68/g' |
sed 's/bide/34/g' |
sed 's/acid/94/g' |
sed 's/fly/52/g' |
sed 's/dig/28/g' |
sed 's/cut/51/g'
