#!/usr/bin/python
import sys
import itertools

def ranges(i):
    for a, b in itertools.groupby(enumerate(i), lambda pair: pair[1] - pair[0]):
        b = list(b)
        yield b[0][1], b[-1][1]

myfile = sys.argv[1]
f = open(myfile, "r")
ascii = f.read()
lines = ascii.split("\n")
for line in lines:
  if line != '':
    mystrs = []
    for item in ranges([int(x) for x in line.split("|")]):
      if item[0] == item[1]:
        mystrs.append(str(item[0]))
      elif item[0] == item[1]-1:
        mystrs.append(str(item[0]))
        mystrs.append(str(item[1]))
      else:
        mystrs.append(str(item[0]) + "-" + str(item[1]))
    print("|".join(mystrs))
  else:
    print()
  
